apiVersion: v1               
kind: Pod                    
metadata:
  name: kubia-manual-v2
  labels:
    creation_method: manual
    env: prod     
spec:
  containers:
  - image: chanalex/api-demo:kubia-1.0   
    name: kubia
    ports:
    - containerPort: 8888
      protocol: TCP